apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: github-events
spec:
  github:
    demo:
      repositories:
        - owner: suhasv133
          repository: argocd_test_2025
      webhook:
        endpoint: /push
        port: "12000"
      events:
        - push
