apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: github-sensor
spec:
  dependencies:
    - name: github-dep
      eventSourceName: github-events
      eventName: demo
  triggers:
    - template:
        name: trigger-workflow
        k8s:
          group: argoproj.io
          version: v1alpha1
          resource: workflows
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: triggered-demo-
              spec:
                entrypoint: main
                templates:
                - name: main
                  container:
                    image: alpine:3.18
                    command: ["sh", "-c"]
                    args: ["echo Triggered from GitHub Webhook!"]
